show databases;
create schema tb_al;
use tb_al;
select database();
#drop schema funcionarios;

CREATE TABLE funcionarios (
    id INT AUTO_INCREMENT PRIMARY KEY,  
    apellidos_nombres VARCHAR(255) NOT NULL,  
    telefono_institucional VARCHAR(20), 
    profesion VARCHAR(100),  
    perfil TEXT, 
    cargo VARCHAR(100), 
    decreto VARCHAR(100),  
    enlace_sigep VARCHAR(255),  
    correo_electronico_institucional VARCHAR(255),  
    direccion VARCHAR(255),  
    horario_trabajo VARCHAR(100),  
    enlace_foto VARCHAR(255) 
);

drop table funcionarios;
select * from funcionarios;

INSERT INTO funcionarios 
(apellidos_nombres, telefono_institucional, profesion, perfil, cargo, decreto, enlace_sigep, correo_electronico_institucional, direccion, horario_trabajo, enlace_foto) 
VALUES 
('ABRIL  CORREDOR  JULIAN ANDRES', '', 'Abogado, Especialista en Derechos Humanos y Derecho Internacional Humanitario', 'Abogado especializado en Derechos Humanos y Derecho Internacional Humanitario, y Secretario de Despacho con experiencia en coordinación legal y administrativa.', 'SECRETARIO DE DESPACHO', '', '', 'juridica@sanjosedelguaviare-guaviare.gov.co', '', '', ''),
('AGUILAR GARCIA JOHANNA', '', 'Economia', 'Técnico Administrativo especializado en gestión económica y control financiero, enfocado en optimizar recursos y procesos organizacionales.', 'TECNICO ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('AGUIRRE MATEUS DIDIER LAUREANO', '3125178065', 'Técnico Administrativo', 'Técnico Administrativo y Agente de Tránsito, con experiencia en gestión administrativa y control vial, enfocado en la seguridad y atención al público.', 'AGENTE DE TRANSITO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ALVAREZ ALVAREZ WILSON ALFONSO', '', 'Ingeniero Agroforestal, Especialista en Gerencia de Proyectos', 'Ingeniero Agroforestal y Especialista en Gerencia de Proyectos, con experiencia en la gestión y desarrollo de proyectos agroindustriales sostenibles.', 'PROFESIONAL UNIVERSITARIO 03', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ARANGO HOYOS NORBEY', '', 'Tecnólogo en Administración de Empresas', 'Tecnólogo en Administración de Empresas y Guardián Municipal, con experiencia en gestión administrativa y seguridad pública. Habilidades en coordinación de operaciones y atención a la comunidad.', 'GUARDIAN MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ARROYO ARROYO ALBEIRO MIGUEL', '3107737815', 'Administrador de Empresas, Especialista en Gestión Pública', 'Administrador de Empresas y Especialista en Gestión Pública, con experiencia en la administración de recursos y coordinación de secretarías de despacho.', 'SECRETARIOS DE DESPACHO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('BARRERA GÓMEZ YURANY MARCELA', '3108643110', 'Ingteniero Agroforestal', 'Ingeniero Agroforestal con experiencia en proyectos agroambientales y apoyo administrativo en secretarías de despacho.', 'SECRETARIOS DE DESPACHO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('BELTRAN BUSTOS JULIO', '', 'N/A', 'Celador Municipal con experiencia en la vigilancia y seguridad de espacios públicos, garantizando el orden y la tranquilidad en la comunidad.', 'CELADOR MUNICIPAL', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('BENTO RAMIREZ MAURICIO', '', 'Técnico Profesional en Construcción de Edificaciones', 'Técnico Profesional en Construcción de Edificaciones con experiencia como ayudante, apoyando en la ejecución y supervisión de obras de construcción.', 'AYUDANTE', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('BERNAL CASTAñEDA AMALIA YANETH', '', 'Administrador Público', 'Administrador Público con experiencia como Secretario Ejecutivo, gestionando procesos administrativos y coordinando actividades en el ámbito gubernamental.', 'SECRETARIO EJECUTIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('BETANCOURT GAMBOA MAURICIO', '', 'Técnico Electricista', 'Técnico Electricista Ayudante con experiencia en instalación, mantenimiento y reparación de sistemas eléctricos, garantizando seguridad y calidad en el trabajo.', 'AYUDANTE', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('BOHADA BELTRAN JOHAN ANDERSSON', '', 'Bachiller', 'Bachiller y Celador Municipal con habilidades en vigilancia, control y prevención de riesgos, asegurando el cumplimiento de normativas y la seguridad en el entorno público.', 'CELADOR MUNICIPAL', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('BOHORQUEZ ROCHA GISELA', '', 'Tecnólogo en Administración de Empresas', 'Tecnólogo en Administración de Empresas con experiencia como Auxiliar Administrativo, enfocado en optimizar procesos, manejo de documentación y atención al cliente.', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('BOHORQUEZ RODRIGUEZ PAULA ANDREA', '', 'Técnico en Asistencia Financiera', 'Técnico en Asistencia Financiera con experiencia como Secretario del Despacho, especializado en la gestión de documentos, atención telefónica y apoyo en la organización de procesos financieros.', 'SECRETARIO DEL DESPACHO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('CAICEDO GUTIERREZ LIZETH MARGARITA', '', 'Contadora Pública', 'Contadora Pública con experiencia como Tesorero, especializada en la gestión financiera, control de presupuestos y administración de recursos económicos en entornos corporativos.', 'PROF. UNIVERSITARIO - TESORERO', '', '', 'hacienda@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('CANO PENAGOS ALEYDA', '', 'Tecnico en Mantenimiento en equipos de computo', 'Técnico en Mantenimiento de Equipos de Cómputo con experiencia como Secretario Ejecutivo, especializado en la gestión administrativa, soporte técnico y coordinación de actividades en entornos corporativos.', 'SECRETARIO EJECUTIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('CARDONA FERIA TIFANNY BRISETH', '', 'Administrador Público', 'Administrador Público con experiencia como Auxiliar Administrativo, especializado en gestión de procesos y organización de documentos.', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('CARRILLO ANGEL JHAN FRANCO', '3209318895', 'Tecnólogo en Gestión Documental', 'Tecnólogo en Gestión Documental con experiencia como Técnico Administrativo, especializado en organización, archivo y manejo eficiente de documentación.', 'TECNICO ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('CASTELLANOS AGUDELO HECTOR LEONARDO', '', 'Técnico Profesional en Administración de Servicios Financieros', 'Técnico en Administración de Servicios Financieros con experiencia como Auxiliar Administrativo, enfocado en gestión financiera y organización de documentos.', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('COLORADO IBARRA JAIR ANTONIO', '', 'N/A', 'Conductor de volqueta con experiencia en el transporte y manejo seguro de materiales, garantizando eficiencia y cumplimiento de normativas de seguridad vial.', 'CONDUCTOR VOLQUETA', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('CONTRERAS RODRIGUEZ JUAN CARLOS', '3112261480', 'Ingeniero Industrial, Ingeniero Mecánico y Especialista en Administración de Salud Ocupacional', 'Ingeniero Industrial y Mecánico, con especialización en Administración de Salud Ocupacional, enfocado en optimizar procesos y garantizar la seguridad laboral.', 'PROFESIONAL UNIVERSITARIO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('CORREA MONTES FERNANDO', '', 'Bachiller', 'Bachiller con experiencia como ayudante, comprometido, proactivo y dispuesto a aprender, con habilidades para apoyar en diversas tareas y colaborar eficientemente en equipo.', 'AYUDANTE', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('COY MARIN WILLIAM CAMILO', '3028078504', 'Derecho', 'Inspector Municipal de Policía en Derecho, especializado en el cumplimiento de normativas y seguridad ciudadana, con habilidades en investigación y coordinación interinstitucional.', 'INSPECTOR MUNICIPAL DE POLICIA', 'Resolución No.128 del 28 de febrero de 2024', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Transversal 21, Calle 23 - Barrio la Esperanza', '', '' ),
('CUESTA MARTINEZ MARCELA VIVIANA', '', 'Bachiller', 'Bachiller en Auxiliar de Servicios Generales, responsable y eficiente en apoyo administrativo y mantenimiento básico.', 'AUXILAIR SERVICIOS GENERALES', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('DIAZ ACOSTA DEISSON GABRIEL', '', 'Técnico Laboral en Sistemas', 'Técnico Laboral en Sistemas y Auxiliar Administrativo, con habilidades en gestión de datos, soporte técnico y administración eficiente de procesos.', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('DURAN PINZON MARINA', '', 'Bachiller', 'Bachiller en Auxiliar de Servicios Generales, comprometido y eficiente en tareas de apoyo operativo y mantenimiento', 'AUXILAIR SERVICIOS GENERALES', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ECHEVERRY GIRALDO WILSON', '', 'Bachiller', 'Bachiller en Celador Municipal, responsable y proactivo en la vigilancia y seguridad de espacios públicos, garantizando el orden y cumplimiento de normativas locales.', 'CELADOR MUNICIPAL', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ECHEVERRY MUÑOZ MERLIN', '', 'Técnico en Obras Civiles y Manejo Ambiental', 'Técnico en Obras Civiles y Manejo Ambiental, con experiencia como ayudante, colaborando en la ejecución de proyectos y el manejo responsable de recursos ambientales.', 'AYUDANTE', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('FONSECA GARCIA SYILVIA NAYDU', '3209094795', 'Médico, Especialista en Gerencia en Salud, Especialista en Diagnostico por Imágenes', 'édico con Especialización en Gerencia en Salud y Diagnóstico por Imágenes, con experiencia en la gestión administrativa y apoyo en la organización de despachos médicos.', 'SECRETARIOS DE DESPACHO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('FRANCO LOAIZA JHON ALBERTO', '', 'Administrador Público Territorial', 'Administrador Público Territorial con habilidades en gestión administrativa y apoyo operativo, enfocado en la optimización de procesos y el buen funcionamiento de entidades públicas.', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('GALEANO BOTERO MARGARITA MARIA', '', 'Gestion de Recursos Naturales', '', 'SECRETARIO EJECUTIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('GALEANO SARMIENTO CAROLINA', '3175094065', 'Abogada, Especialista en Derecho Procesal, Magister en Justicia y Tutela de los Derechos', '', 'COMISARIO DE FAMILIA', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '', '' ),
('GALLEGO AGUIRRE LUZ GICELA', '', 'Contadora Pública, Especialista en Finanzas', '', 'PROFESIONAL UNIVERSITARIO - CO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('GARCIA YASMO EDWAR MAURICIO', '', 'Técnico Profesional en Administracion', '', 'GUARDIAN MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('GAVIRIA PABON YERLI SIOMARA', '', 'Administrador de Recursos Humanos', '', 'AUXILAIR SERVICIOS GENERALES', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('GODOY DIAZ NORMA JANETH', '', 'Abogada, Especialista en Derecho Público', '', 'PROFESIONAL UNIVERSITARIO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('GOMEZ ANGARITA GERMAN', '', 'Administrador Público', '', 'CORREGIDOR', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('GOMEZ HOLGUIN WILMAR CLEMENTE', '3142267173', 'Ingeniero Industrial, Especialista en estadistica aplicada, Especialista en Gestion de Proyectos', '', 'TECNICO ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('GUEVARA RODRIGUEZ ALBA LUCIA', '', 'Bachiller', '', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('GUTIERREZ GÓMEZ KEVIN ANDRES', '3133859298', 'Ingeniero Civil', '', 'SECRETARIO DE DESPACHO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('HERNANDEZ BARBOSA YORMAIRA', '', 'Tecnologo en Contabilidad y Finanzas', '', 'SECRETARIO EJECUTIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('HERNANDEZ CASAS JHONATAN ANDRES', '', 'Bachiller', '', 'CELADOR MUNICIPAL', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('HERNANDEZ MEJIA LUIS CARLOS', '', 'Bachiller', '', 'INSPECTOR DE OBRAS PÚBLICAS', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('HERNANDEZ MENDOZA MARÍA JOSÉ', '', 'Trabajadora Social', '', 'PROFESIONAL UNIVERSITARIO 03', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('HERNANDEZ SEGURA MAYRA ANDREA', '', 'Abogada, Especialista en Derecho Administrativo, Especialista en Contratación Estatal', '', 'PROFESIONAL ESPECIALIZADO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('HERRERA TICORA RODOLFO', '', 'Administrador de Empresas, Tecnico profesional en mantenimiento de hardware', '', 'TECNICO ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('IBARRA OLARTE MEYLI YULEYMA', '', 'Administrador de Empresas, Tecnólogo en Gestión Administrativa', '', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('JIMENEZ OSORIO LUIS FELIPE', '', 'Tecnologo en Ciencias', '', 'GUARDIAN MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('LAGOS AGUILAR YINA MARCELA', '', 'Bachiller', '', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('LARROTA MORENO YOLVER DAVID', '', 'Bachiller', '', 'CONDUCTOR', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('LONDOÑO MORALES DIANA MILENA', '3017774695', 'Abogada, Especialista en Administracion Aeronautica y Aeroespacial', '', 'JEFE OFICINA DE CONTROL INTERNO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('LOPEZ VELASCO JACKELINE', '', 'Bachiller', '', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MAHECHA VASQUEZ ALEIDA', '', 'Administradora de Empresas', '', 'SECRETARIO EJECUTIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MAYORGA BAUTISTA LAURA CONSTANZA', '3134991270', 'Comunicadora Social, Especialista en Gerencia de Producción de Medio de Comunicación', '', 'SECRETARIO DE TRANSITO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MEJIA CAYCEDO LEOPOLDO', '3203421890', 'Abogado, Especialista en Alta Gerencia y Economía Solidaria', '', 'JEFE OFICINA DE CONTROL INTERNO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MENA MORENO CARLOS ARTURO', '', 'Administrador de empresas, Especialista en Gestion para el Desarrollo empresarial', '', 'TÉCNICO OPERATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MERCHAN CAÑON ALBA MARINA', '', 'Administrador Financiero, Técnico en Nomina y prestaciones sociales', '', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MONDRAGON GOMEZ HERNAN DARIO', '', 'Técnico en Mantenimiento de Sistemas, Tecnólogo en Analisis y Desarrollo de Sistemas', '', 'GUARDIAN MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MONROY BERNAL JESSICA YINETH', '', 'Administrador de empresas, Tecnologo en Gestion del Talento Humano', '', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MORA PABLO ENRIQUE', '', 'N/A', '', 'MECÁNICO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MORALES REYES GLORIA YANETH', '', 'Administradora Pública', 'INSPECTOR DE PLANEACION', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '', '' ),
('MOSQUERA MORALES ARIEL', '3183971528', 'Administrador Público, Especialista en Gestion u Planificacion de Política Social, Maestria en Politicas Sociales, Especialista en Gestion ambiental', '', 'SECRETARIOS DE DESPACHO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('MURILLO RAMIREZ PORFILIO', '3168749621', 'Licenciado en Educación básica con enfasis en educacion fisica, recreacion y deportes, Especialista en Administracion de la Informatica Educativa', 'SECRETARIOS DE DESPACHO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '', '' ),
('NIETO MORA JHON ALEXANDER', '3173684226', 'Contador Público', '', 'DIRECTOR IMDES', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('NOVOA DIAZ JENNIFER YULIET', '', 'Contadora Pública, Especialista en Revisoria Fiscal y Auditoria Forense', 'TECNICO ADMINISTRATIVO', 'L', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '', '' ),
('OLIVAR PAYANENE CESAR ANDRES', '', 'Bachiller', '', 'GUARDIAN MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('OSORIO VELANDIA SANDRA PATRICIA', '', 'Administradora de empresas, Tecnologa en Gestion de Recursos Naturales', '', 'TÉCNICO OPERATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('OSPINA HUERTAS JOSE LUIS', '', 'Bachiller', '', 'CONDUCTOR VOLQUETA', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('OTALORA GUTIERREZ FERNANDO', '3222551384', 'Tecnologo en Gestion Administrativa, Tecnico Laboral en Trabajo Social y Comunitario', '', 'ALMACENISTA', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('PARDO NORATO NOLBERTO', '', 'Bachiller', '', 'CELADOR MUNICIPAL', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('PARRA DE SANCHEZ ANA BEATRIZ', '', 'Bachiller', '', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('PEREZ BELTRAN ORLANDO', '', 'Bachiller', '', 'OPERADOR DE MAQUINARIA 1', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('PEREZ ORJUELA ANACELIS', '', 'Bachiller', '', 'SECRETARIO EJECUTIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('PIZO CAICEDO JOSE SEBASTIAN', '', 'Tecnólogo en Control y Seguridad Vial', '', 'AGENTE DE TRANSITO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('PORTELA SERRATO TANIA YULIETH', '', 'Psicologa', '', 'PROFESIONAL UNIVERSITARIO 03', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('QUIMBAYO OSPINA JOSE ANTONIO', '', 'Bachiller', '', 'GUARDIAN MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('QUIROZ DURAN JORGE IVAN', '', 'Administrador de empresas, Maestria en Administracion y Políticas Públicas', '', 'DIRECTOR CÁRCEL MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('RENDON MIRANDA LORENA CLEMENTINA', '', 'Técnico en Administración Pública', '', 'AUXILAIR SERVICIOS GENERALES', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('RESTREPO TORO DOLLY ESPERANZA', '', 'Técnico Profesional en Administración de Talento Humano', '', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('RIVERA FLORES GILBERTO ALEXI', '', 'Bachiller', '', 'OPERADOR DE MAQUINARIA 1', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('RODRIGUEZ GONZALEZ NIYERETH', '', 'Tecnólogo en Gestion Administrativa', '', 'SECRETARIO EJECUTIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('RODRIGUEZ ROJAS ANGELICA YULIETH', '', 'Licenciada en Música', '', 'PROFESIONAL UNIVERSITARIO 03', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('RODRÍGUEZ ROJAS WILLY ALEJANDRO', '3103413509', 'Zootecnista, Especialista en Gobierno y Gestion Pública Territorial', '', 'ALCALDE MUNICIPAL', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('RODRIGUEZ TRIANA LUIS', '', 'Bachiller', '', 'OPERADOR DE MAQUINARIA 1', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ROJAS CARDONA ZUNILDA', '', 'Bachiller', '', 'AUXILIAR ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ROMERO MURCIA ANGELICA JHOANA', '3214739154', 'Contadora Pública', '', 'TECNICO ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('SANABRIA OMAÑA VIRGILIO', '', 'Bachiller', '', 'AYUDANTE', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('SANCHEZ VARGAS CARLOS FAVIO', '', 'Bachiller', '', 'GUARDIAN MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('SERRANO CARDONA PEDRO LUIS', '', 'Bachiller', '', 'OPERADOR DE MAQUINARIA 2', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('SILVA GARZON MILTON FARLEY', '', 'Tecnico en Promocion Ambiental', '', 'GUARDIAN MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('TOVAR CORTES MARIA ELVIRA', '', 'Economista, Especialista en Contratación Estatal', '', 'SECRETARIO EJECUTIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('VALDERRAMA MURCIA RICARDO ANDRES', '', 'Administrador de Empresas, Administrador de Empresas Agropecuarias', '', 'PROFESIONAL UNIVERSITARIO 03', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('VALLEJO ALFONSO SEBASTIAN', '', 'Técnico en Asistencia Administrativa', '', 'AYUDANTE', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('VALOYES BENITEZ LEDYS MAGALI', '', 'Administradora Ambiental', '', 'SECRETARIO EJECUTIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ELANDIA SALCEDO JUAN CARLOS', '', 'Ingeniero Civil', '', 'DIRECTOR TECNICO OBRAS', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('VERGARA URREGO CEIDA', '3164660379', '', 'Administradora Pública, Especialista en Gestion Pública', '', 'SECRETARIOS DE DESPACHO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '' ),
('VILLADA VALENCIA BLANCA AYDEE', '', 'Tecnólogo en Salud Ocupacional, Tecnólogo en Construcción', '', 'TECNICO ADMINISTRATIVO', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ILLALOBOS URREGO SANDRA CAROLINA', '', 'Administradora de Empresas Agropecuarias', '', 'CORREGIDOR', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('YEPES PORRAS LUISA DELIA', '', 'Bachiller', '', 'AUXILAIR SERVICIOS GENERALES', '', '', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', '', '', '' ),
('ZULETA LEGUISAMO CARLOS ENRIQUE', '', 'Bachiller', '', 'GUARDIAN MUNICIPAL', '', '', 'carcel@sanjosedelguaviare-guaviare.gov.co', '', '', '' );



