show databases;
create schema tb_al;
use tb_al;
select database();
#drop schema funcionarios;

CREATE TABLE funcionarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    apellidos_nombres VARCHAR(255) NOT NULL,
    telefono_institucional VARCHAR(20),
    profesion VARCHAR(100),
    perfil TEXT,
    cargo VARCHAR(100),
    decreto VARCHAR(100),
    enlace_sigep VARCHAR(255),
    correo_electronico_institucional VARCHAR(255),
    direccion VARCHAR(255),
    horario_trabajo VARCHAR(100),
    enlace_foto VARCHAR(255),

    CHECK (CHAR_LENGTH(apellidos_nombres) > 5),
    CHECK (correo_electronico_institucional LIKE '%@%')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

drop table funcionarios;
select * from funcionarios;

INSERT INTO funcionarios 
(id, apellidos_nombres, telefono_institucional, profesion, perfil, cargo, decreto, enlace_sigep, correo_electronico_institucional, direccion, horario_trabajo, enlace_foto) 
VALUES 
('1','AGUILAR GARCIA JOHANNA', '3114567890', 'ECONOMISTA', 'Economista técnico administrativo, enfocado en la gestión de recursos y análisis económico.', 'TECNICO ADMINISTRATIVO', 'Resolución No. 1047 del 24 de noviembre de 2022', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1152109-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 19-115 barrio El Porvenir', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.','https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EY-0jSt_kNBOogfepjdztNEBudXOCR5ky_sLDHM-REg_QA?e=pYa9hY'),
('2','ALVAREZ ALVAREZ WILSON ALFONSO', '3149876543', 'INGENIERO AGROFORESTAL', 'Ingeniero agroforestal, especializado en la gestión sostenible de recursos naturales.', 'PROFESIONAL UNIVERSITARIO 03', 'Resolución No. 953 del 22 de diciembre de 2023', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1157623-1039-4/view', 'juridica@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.','https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/NzXqRpFv6KdFe1LpXQMK98KqW6vL8owtEYjfT5HgPoOWeQ?e=RnMbZ7'),
('3','ARANGO HOYOS NORBEY', '3156789012', 'TECNÓLOGO EN ADMINISTRACIÓN DE EMPRESAS', 'Tecnólogo en Administración de Empresas y Guardián Municipal, con enfoque en gestión y seguridad pública.', 'GUARDIAN MUNICIPAL', 'Resolución No. 956 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1157626-1039-4/view', 'carcel@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro','Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.','https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EUrQCqgQ9vJJnY8fUphSKg8BJPgzwf20LcUFXpy3E0Lamg?e=BjplHc'),
('4','ARROYO ARROYO ALBEIRO MIGUEL', '3163456789', 'ADMINISTRADOR DE EMPRESAS', 'Bachiller y Celador Municipal con experiencia en vigilancia y apoyo en tareas administrativas en el ámbito local.', 'SECRETARIOS DE DESPACHO', 'Decreto No. 001 del 01/01/2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1930898-1039-4', 'administrativa@sanjosedelguaviare-guaviare.gov.co', 'Calle 8 # 23 - 87 - barrio El Centro 2do piso', 'Lunes a viernes de 8:00 a.m. a 12:30 p.m. y de 2:00 a 6:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EQv3iSb3i7pChhXXkoTDs7ABVzzl-Lf_CI7FCV907Jcgqw?e=x2fkX2'),
('5','BELTRAN BUSTOS JULIO', '3174567890', 'BACHILLER', 'Técnico en Construcción Ayudante con experiencia en apoyo y tareas en obras, garantizando calidad y seguridad.', 'CELADOR MUNICIPAL', 'Decreto No. 038 del 13 de marzo de 2002', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1157630-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Calle 9D # 19-50 barrio El Centro', 'Lunes a viernes de 7:00 a.m. a 12:00 m. y 2:00 a 5:00 p.m.','https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/BpQrX9DjOvFZvcJ4WyFkj64D7vIqnAJxuHqEKkPfLMuU1Q?e=WmXtHr'),
('6','BOHADA BELTRAN JOHAN ANDERSSON', '3211234567', 'BACHILLER', 'Bachiller y Celador Municipal, con experiencia en apoyo administrativo y vigilancia en el ámbito municipal.', 'CELADOR MUNICIPAL', 'Resolución No. 948 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S2953328-1039-4/view', 'administrativa@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/XrFpAqB9JvWyKL1xEmn9HDAU86rPdwZyHscUbPQKwT8RZw?e=KjLmWd'),
('7','CAICEDO GUTIERREZ LIZETH MARGARITA', '3233456789', 'CONTADORA', 'Contadora Profesional Universitaria, con experiencia en gestión financiera y contable.', 'PROFESIONAL UNIVERSITARIO 03', 'Decreto No. 145 del 28 de junio de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1930898-1039-4', 'hacienda@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EadQmZCiMQNItzYRZ028u6kB03CUNFEA87IF06q1-6T9hw?e=rvnRvy'),
('8','CANO PENAGOS ALEYDA', '3244567890', 'TECNICO EN MANTENIMIENTO DE EQUIPOS DE COMPUTO', 'Técnico en Mantenimiento de Cómputo y Secretario Ejecutivo, con enfoque en soporte y gestión.', 'SECRETARIO EJECUTIVO', 'Resolución No. 987 del 9 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep/hdv/-/directorio/S703599-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 19-115 barrio El Porvenir', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EZTFqRlY2edNtFkin7dRNe4B7dvPoFXSiLnEPP8ag-DsqA?e=pgEDYN'),
('9','CARDONA FERIA TIFANNY BRISETH', '3255678901', 'ADMINISTRADORA PÚBLICA', 'Administradora Pública con experiencia en gestión administrativa y optimización de recursos.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 963 del 8 de noviembre de 2022', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1808076-1039-4', 'administrativa@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/ESVe5fRy6JBPrSOLMgFLKt4BK3XM15TWBvGEhORckjvqoQ?e=cGOLO9'),
('10','CARRILLO ANGEL JHAN FRANCO', '3266789012', 'TECNOLOGO EN GESTION DOCUMENTAL', 'Tecnólogo en Gestión Documental y Técnico Administrativo, especializado en organización de la información.', 'TECNICO ADMINISTRATIVO', 'Resolución No. 958 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S4628485-1039-4/view', 'obraspublicas@sanjosedelguaviare-guaviare.gov.co', 'Calle 8 # 23 - 87 - barrio El Centro 1er piso', 'Lunes a viernes de 8:00 a.m. a 12:30 p.m. y de 2:00 a 6:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EcK-n5cQC6hHoiHXbhDQKkwBeikdWEToHJDszg7XW8DIWw?e=5wWfjU'),
('11','CASTELLANOS AGUDELO HECTOR LEONARDO', '3277890123', 'TECNICO EN ADMINISTRACION DE SERVICIOS FINANCIEROS', 'Técnico en Administración de Servicios Financieros y Auxiliar Administrativo, enfocado en gestión financiera.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 038 del 29 de septiembre de 1999', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S885168-1039-4/view', 'obraspublicas@sanjosedelguaviare-guaviare.gov.co', 'Calle 9D # 19-50 barrio El Centro', 'Lunes a viernes de 7:00 a.m. a 12:00 m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Ebcl7ePTozxOssEHCGQ2TgwBWFc2NCEDCGlwlBWOC68Ywg?e=z9TdUe'),
('12','CONTRERAS RODRIGUEZ JUAN CARLOS', '3299012345', 'INGENIERO MECANICO, INDUSTRIAL, ESPECIALISTA EN ADMINISTRACION DE SALUD OCUPACIONAL', 'Ingeniero Mecánico e Industrial, especialista en Salud Ocupacional.', 'PROFESIONAL UNIVERSITARIO', 'Resolución No. 1039 del 24 de noviembre de 2022', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1930898-1039-4', 'obraspublicas@sanjosedelguaviare-guaviare.gov.co', 'Calle 8 N° 23 - 87, barrio El Centro 2do piso', 'Lunes a viernes de 8:00 a.m. a 12:30 p.m. y de 2:00 a 6:00 p.m.','https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Ebcl7ePTozxOssEHCGQ2TgwBWFc2NCEDCGlwlBWOC68Ywg?e=z9TdUe'),
('13','COY MARIN WILLIAM CAMILO', '3012345678', 'DERECHO', 'Profesional en Derecho, Inspector Municipal de Policía con experiencia en normatividad y gestión pública.', 'INSPECTOR MUNICIPAL DE POLICIA', 'Resolución No. 128 del 28 de febrero de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S4891526-1039-4', 'administrativa@sanjosedelguaviare-guaviare.gov.co', 'Calle 8 N° 23 - 87, barrio El Centro 1er piso', 'Lunes a viernes de 8:00 a.m. a 12:00 p.m. y de 2:00 a 4:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Ee3cgE-GOtJKkWVjF9UrYK8B548WLIg8z_2AGpEHFTEL-g?e=yy7lT7'),
('14','DIAZ ACOSTA DEISSON GABRIEL', '3034567890', 'TECNICO LABORAL EN SISTEMAS', 'Técnico en Sistemas con experiencia como Auxiliar Administrativo y manejo de herramientas ofimáticas.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 977 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S2561015-1039-4/view', 'carcelmunicipal@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EUryw_qt2HlKmshJAff6V34BTtpRL6FD4Cc7FdwxsGbGmA?e=jx5Lrf'),
('15','DURAN PINZON MARINA', '3045678901', 'BACHILLER', 'Bachiller con experiencia como Auxiliar en Servicios Generales y apoyo operativo.', 'AUXILAIR SERVICIOS GENERALES'	, 'Resolución No. 859 del 20 de noviembre de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S2368124-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/WhYzXmJKpVFeKQ2uLZcQbNd7pTlJrvfGYMKqaJbPvOYAbQ?e=XzLnUb'),
('16','ECHEVERRY GIRALDO WILSON', '3056789012', 'BACHILLER', 'Bachiller con experiencia como Celador Municipal y vigilancia de bienes públicos.', 'CELADOR MUNICIPAL', 'Resolución No. 954 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S704811-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/ESUA_RGtGl9BthTiLhW3gcoB_3J2zuNtoq0sUD6c2BK9AA?e=Zs5Xco'),
('17','ECHEVERRY MUÑOZ MERLIN', '3067890123', 'BACHILLER', 'Bachiller con experiencia como Ayudante en labores operativas y de apoyo general.', 'AYUDANTE', 'Contrato Individual de Trabajo a Términio Indefinido ', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1930898-1039-4', 'obraspublicas@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EVYaqkiGImBGnK9EL1iZRwMB0fUNri25Yey00-McKErgQQ?e=GTUmPG'),
('18','FONSECA GARCIA SYILVIA NAYDU', '3078901234', 'MEDICA, ESPECIALISTA EN GERENCIA EN SALUD', 'Especialista en Gerencia en Salud con experiencia en gestión administrativa y liderazgo en secretarías de despacho.', 'SECRETARIOS DE DESPACHO', 'Decreto No. 003 del 01 de enero de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S352452-1039-4', 'salud@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.','https://soysena-my.sharepoint.com/:u:/g/personal/luisaf_barbosas_soy_sena_edu_co/EbxbQJducnZCuHirUCTG8S8BB9uLrtdfBOYyDJKmEs607w?e=k6XDCK'),
('19','FRANCO LOAIZA JOHN ALBERTO', '3089012345', 'ADMINISTRADOR PÚBLICO', 'Administrador Público con experiencia en gestión y soporte administrativo en el sector público.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 035 del 17 de marzo de 2004', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1157643-1039-4', 'hacienda@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EfXClyFbPWpPrp-72heyxB0BB8JMBps9XT8A6fJ5iN3iiw?e=5lAC1G' ),
('20','GALEANO BOTERO MARGARITA MARIA', '3090123456', 'TECNOLOGO EN GESTION DE RECURSOS NATURALES', 'Tecnólogo en Gestión de Recursos Naturales y Secretario Ejecutivo, enfocado en administración sostenible.', 'SECRETARIO EJECUTIVO', 'Resolución No. 663 del 31 de agosto de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S918326-1039-4', 'planeacion@sanjosedelguaviare-guaviare.gov.co', 'Carrera 26 # 8-90, barrio El Centro', 'Lunes a Viernes De 8:00 a.m. a 12:00 m. Y De 2:00 p.m. a 6:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EXc2pd6pr8dOrhfbZamSNGYBNRAQIdDMaB3Aq3U2rtkMog?e=WvCqwN' ),
('21','GALEANO SARMIENTO CAROLINA', '3123456789', 'ABOGADA, ESPECIALISTA EN DERECHO PROCESARL, MAESTRIA EN JUSTICIA Y TUTELA DE LOS DERECHOS', 'Abogada, Comisaria de Familia y especialista en Justicia y Tutela de los Derechos.', 'COMISARIO DE FAMILIA MUNICIPAL', 'Resolución No. 678 del 6 de septiembre de 2023', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1420557-1039-4/view', 'comisariadefamilia@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/CqJxTVgRmLiFzuW8MABoHRqvN7dFPylCxRMgZqUkWyQaKw?e=UkFbPv'),
('22','GALLEGO AGUIRRE LUZ GICELA', '3134567890', 'CONTADORA PUBLICA, ESPECIALISTA EN FINANZAS', 'Contadora Pública, especialista en Finanzas y Profesional Universitario en CO.', 'PROFESIONAL UNIVERSITARIO - CO', 'Decreto No. 012 del 13 de enero de 1998', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1157645-1039-4/view', 'hacienda@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/KpFzRoXtLnDqHVRG92JxgKoLzExaYnBmPUYZhXqMcEa9KA?e=JqRvTu'),
('23','GARCIA YASNO EDWAR MAURICIO', '3145678901', 'BACHILLER', 'Bachiller y Guardián Municipal, enfocado en la seguridad comunitaria.', 'GUARDIAN MUNICIPAL', 'Resolución No. 950 del 8 de noviembre de 2022', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1930898-1039-4', 'carcel@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Ecg6uLWdfAFOihvPOTBRkVIBOSrre07IwSQ78gyuL9ODZA?e=ODbs1R'),
('24','GAVIRIA PABON YERLI SIOMARA', '3156789012', 'TECNICO EN NOMINA Y PRESTACIONES SOCIALES', 'Técnico en Nómina y Prestaciones Sociales, con experiencia como auxiliar en servicios generales.', 'AUXILAIR SERVICIOS GENERALES', 'Resolución No. 857 del 20 de noviembre de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S4799243-1039-4', 'carcelmunicipal@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/PzAfYcVmQnLKZoFevJcMiUB2ErLtPqTCNhWXyZoUArAbEw?e=ZfMvPu'),
('25','MATEUS CRUZ MARIA JOSE', '3167890123', 'ABOGADA', 'Abogada profesional universitaria, comprometida con la justicia y el asesoramiento legal.', 'PROFESIONAL UNIVERSITARIO', 'Decreto No. 216 de 2024', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S4633305-1039-4/view', 'juridica@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/AvPmUbYjLrKwFyXzNcQoGtLbAxHnMyLvVqRgZaEcWmNyOg?e=WqHkMr'),
('26','GOMEZ HOLGUIN WILMAR CLEMENTE', '3178901234', 'INGENIERO INDUSTRIAL, ESPECIALISTA EN ESTADISTICA APLICADA', 'Ingeniero Industrial con especialización en Estadística Aplicada y experiencia como Técnico Administrativo.', 'TECNICO ADMINISTRATIVO', 'Resolución No. 1045 del 24 de noviembre de 2022', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S341819-1039-4', 'sisben@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/GxRoUfTxAmKjyMW74RcLpPYgBxTzZkUKFSfVoMzCEuDa2A?e=XvTuWm'),
('27','GUEVARA RODRIGUEZ ALBA LUCIA', '3189012345', 'TECNICO EN ADMINISTRACIÓN DE FINANZAS', 'Técnico en Finanzas y Auxiliar Administrativo, con habilidades en gestión.', 'AUXILIAR ADMINISTRATIVO', 'Decreto No. 069 del 26 de diciembre de 1985', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1930898-1039-4', 'planeacion@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EUva5Pxaa6NLiqQdmJFrCJUBfBkuyio2nRNKSHHGhJvfZg?e=ebKwuj'),
('28','HERNANDEZ BARBOSA YORMAIRA', '3201234567', 'TECNOLOGO EN CONTABILIDAD Y FINANZAS', 'Tecnólogo en Contabilidad y Finanzas, con experiencia como Secretario Ejecutivo.', 'SECRETARIO EJECUTIVO', 'Resolución No. 662 del 31 de agosto de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S916869-1039-4', 'comisariadefamilia@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EXj9yxzvOZJCtWx5hd7zH-0B-6NkOyhe48mIPPLuOM3oag?e=F0KGEU'),
('29','HERNANDEZ CASAS JHONATAN ANDRES', '3212345678', 'BACHILLER', 'Bachiller con experiencia como Celador Municipal, encargado de velar por la seguridad y el orden público.', 'CELADOR MUNICIPAL', 'Resolución No. 955 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/directorio#_com_liferay_iframe_web_portlet_IFramePortlet_INSTANCE_M3DL5JqFEfCZ_=https%3A%2F%2Fwww1.funcionpublica.gov.co%2Fweb%2Fsigep2%2Fhdv%2F-%2Fdirectorio%2FS4628037-1039-4%2Fview', 'administrativa@sanjosedelguaviare-guaviare.gov.co', 'Carrera 28 # 8-50, barrio El Centro', 'Lunes a Viernes De 8:00 a.m. a 12:00 m. Y De 2:00 p.m. a 6:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EdSaZyexqXxHoKgW3cR6TE0BQzyPw8IP-3uqrXByslNOfg?e=F4RNTa'),
('30','HERNANDEZ MEJIA LUIS CARLOS', '3223456789', 'BACHILLER', 'Bachiller con experiencia como Inspector, encargado de supervisar y garantizar el cumplimiento de normativas.', 'INSPECTOR', 'Decreto No. 018 del 1 de marzo de 2011', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1158219-1039-4/view', 'obraspublicas@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EeWwC4KxBF5OnM0BRZe01_QB9_iabOOIxXM0aiLO8zUa1Q?e=3Y1Tm3'),
('31','HERNANDEZ MENDOZA MARÍA JOSÉ', '3234567890', 'TRABAJADORA SOCIAL', 'Trabajadora Social profesional universitaria, con experiencia en la atención y gestión de casos sociales.', 'PROFESIONAL UNIVERSITARIO 03', 'Resolución No. 935 del 14 de diciembre de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S3099421-1039-4', 'comisariadefamilia@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/LwVpNqKyEXYgjAroFdZuxmBhLqOcEfRJtLhZCPQuPgV9Fg?e=KpRqDa'),
('32','HERNANDEZ SEGURA MAYRA ANDREA', '3245678901', 'ABOGADA, ESPECIALISTA EN DERECHO ADMINISTRATIVO, ESPECIALISTA EN CONTRATACION ESTATAL', 'Abogada especialista en Derecho Administrativo y Contratación Estatal, con amplia experiencia.', 'PROFESIONAL ESPECIALIZADO', 'Resolución No. 935 del 14 de diciembre de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S779406-1039-4', 'comisariadefamilia@sanjosedelguaviare-guaviare.gov.co', 'Carrera 28 # 8-50, barrio El Centro', 'Lunes a Viernes De 8:00 a.m. a 12:00 m. Y De 2:00 p.m. a 6:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/YtKwAoViHbTRlPU2nVmYkErZGoPqcNUZdFkDjMnBwXtByA?e=DpXqRm'),
('33','HERRERA TICORA RODOLFO', '3256789012', 'ADMINISTRADOR DE EMPRESAS', 'Administrador de Empresas y Técnico Administrativo, con experiencia en gestión y optimización de procesos.', 'TECNICO ADMINISTRATIVO', 'Resolución No. 942 del 8 de noviembre de 2022', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S701207-1039-4', 'salud@sanjosedelguaviare-guaviare.gov.co', 'Carrera 28 # 8-50, barrio El Centro', 'Lunes a Viernes De 8:00 a.m. a 12:00 m. Y De 2:00 p.m. a 6:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/NjRxOmLbAkVyFJzK97LcRaPoEwMqXyYBHzCWrQfUBgLpXw?e=EzSmYc'),
('34','IBARRA OLARTE MEYLI YULEYMA', '3267890123', 'ADMINISTRADORA DE EMPRESAS', 'Administrador de Empresas con experiencia como Auxiliar Administrativo.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 962 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S4630346-1039-4/view', 'administrativa@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/JmRtPoAwXeFZmnX9QlRvKHd4MvQoYzWxUcKqPiZRbFqACQ?e=KwYnLf'),
('35','JIMENEZ OSORIO LUIS FELIPE', '3278901234', 'ADMINISTRADOR PUBLICO', 'Administrador Público con experiencia como Guardián Municipal.', 'GUARDIAN MUNICIPAL', 'Resolución No. 369 del 29 de mayo de 2023', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S3166070-1039-4/view', 'carcel@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/ETUcYQ5LtAtOt-rkOesHRHYB2chq7Xfy9_tkfsOYAcj3qA?e=KBEFoW'),
('36','LAGOS AGUILAR YINA MARCELA', '3289012345', 'BACHILLER', 'Bachiller con experiencia como Auxiliar Administrativo.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 457 del 28 de junio de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S3095614-1039-4', 'hacienda@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EflaEq-FazlIiJDf4tODihABXuCB0qAx0Lx6p1-cRRaDWg?e=3ogWUe'),
('37','LOPEZ GUTIERREZ EDWIN', '3290123456', 'AGRONOMO', 'Agrónomo con experiencia en gestión pública como Secretario de Despacho.', 'SECRETARIOS DE DESPACHO', 'Decreto No. 221 de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S341838-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/QeMzWbYcAzVFqTrPnDbUxKAjLYvMeWnVQxHoLrPyTzZwPw?e=MnLtKb'),
('38','LARROTA MORENO YOLVER DAVID', '3003456789', 'BACHILLER', 'Bachiller con experiencia como conductor responsable y comprometido.', 'CONDUCTOR', 'Decreto No. 036 del 2 de mayo de 2011', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S896953-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/KbQyTfNgLoMzRV1AjYaDvmk2NuHpFeWrTzJeYKMuEnLaAw?e=VgUzQr'),
('39','LONDOÑO MORALES DIANA MILENA', '3014567890', 'ABOGADA, ESPECIALISTA EN ADMINISTRACION AERONAUTICA, MAGISTER EN DERECHO PUBLICO', 'Abogada con posgrados en Derecho Público y Administración Aeronáutica, y experiencia como Jefe de Control Interno', 'JEFE OFICINA DE CONTROL INTERNO', 'Decreto No. 011 del 1 de enero de 2024', 'https://www1.funcionpublica.gov.co/web/sigep2/directorio', 'desarrolloproductivoyambiental@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/ES45h5phkD9Bv0A_gTC03oIBVqR1G8-IYOmGq3nv2Mwnow?e=i3QfPY'),
('40','LOPEZ VELASCO JACKELINE', '3025678901', 'BACHILLER', 'Bachiller con experiencia como auxiliar administrativo.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 265 del 26 de abril de 2024', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S947853-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EXCNRrKxz09EkOvtCIANrHYBGfeQWeOIBX9Sd7wbCJohbA?e=1041Jg'),
('41','MARCHENA ORTEGA ENITH MILENA', '3047890123', 'ABOGADA', 'Abogada especializada en asesoría legal para secretarías de despacho y gestión de procedimientos administrativos.', 'SECRETARIOS DE DESPACHO', 'Decreto No. 216 de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S864352-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/XcAyFoNjBwDzVrXpKqYiLmVgTrEhMzAaPwRjGnZpTyOcKg?e=LuYnVs'),
('42','ACEVEDO ORTEGA DANIEL EDGARDO', '3058901234', 'INGENIERO CIVIL, ESPECIALISTA EN GERENCIA DE PROYECTOS DE CONSTRUCCION E INFRAESTRUCTURA', 'Ingeniero Civil, especialista en Proyectos y Secretario de Tránsito, con experiencia en infraestructura y movilidad.', 'SECRETARIO DE TRANSITO', 'Decreto No. 044 del 12 de marzo de 2025', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S2816173-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 19-115 barrio El Porvenir', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/QWs89dKp3LMnj23zXeiPJGfH20qvXkYzlYwUErZ2rFhTug?e=YkN2rD'),
('43','MEJIA CAYCEDO LEOPOLDO', '3069012345', 'ABOGADO', 'Abogado y Jefe de Control Interno, experto en gestión legal y cumplimiento.', 'JEFE OFICINA CONTROL INTERNO D', 'Decreto No. 177 del 29 de diciembre de 2017', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S416490-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EbAChGAMra1Evhk3ZBdMebUB-Nczci4ExtQ_ikZ8x-EvkQ?e=Hc5VrJ'),
('44','MENA MORENO CARLOS ARTURO', '3070123456', 'ADMINISTADOR DE EMPRESAS', 'Administrador de Empresas con enfoque técnico operativo, especializado en optimización de procesos y gestión de recursos.', 'TÉCNICO OPERATIVO', 'Resolución No. 185 del 26 de junio de 1997', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S2775379-8020-5', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/BnFkHtZpCvMnKwRaDqTuZmFvOaTxLpFgGjRmWuKsZhXoPg?e=RfKtWc'),
('45','MERCHAN CAÑON ALBA MARINA', '3081234567', 'ADMINISTRADORA FINANCIERA', 'Administradora financiera con experiencia en gestión y apoyo administrativo.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 961 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S2079016-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/ESSbnXJWq1JOu1uaXRXIxJ8BarxSulA6c8F9OrX21P64Eg?e=CiSa76'),
('46','MONDRAGON GOMEZ HERNAN DARIO', '3092345678', 'TECNICO EN MANTENIMIENTO DE MOTOCICLETAS','Técnico en mantenimiento de motocicletas y guardia municipal, con experiencia en reparación y vigilancia.', 'GUARDIAN MUNICIPAL', 'Resolución No. 945 del 8 de noviembre de 2022', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1639611-1039-4', 'carcel@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EaX4NKp4K1dCpOh0ZwRPP_QBlAgzqBayNAuDqNuVeKCL_Q?e=4JTe9d'),
('47','MONROY BERNAL JESSICA YINETH', '3103456789', 'ADMINISTRADORA DE EMPRESAS', 'Administradora de empresas con experiencia en gestión organizacional y apoyo administrativo eficiente.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 665 del 31 de agosto de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S2035967-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 28 # 8-50, barrio El Centro', 'Lunes a Viernes De 8:00 a.m. a 12:00 m. Y De 2:00 p.m. a 6:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/ER6Quq7lF-9AvnJgT0xOj2cBWqNVGQ1hNgBD0HJIe0FXnQ?e=JJqX1O'),
('48','MONTAÑEZ ACEVEDO DIANA ANDREA', '3115678901', 'ADMINISTRADORA DE EMPRESAS', 'Administradora de empresas con experiencia en gestión y coordinación como secretaria general del despacho.', 'SECRETARIA GENERAL DEL DESPACHO', 'Decreto No. 237 del 31 de diciembre de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1158224-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/NyQmDzArKxYtJwPnXbViLuOzNpTfMbQyLtRgHeZoFwKvMg?e=BtDxFv'),
('49','MOSQUERA MORALES ARIEL', '3137890123', 'ADMINISTRADOR PÚBLICO, ESPECIALISTA EN GESTION Y PLANIFICACION DE POLÍTICA SOCIAL, MAESTRIA EN POLICITVAS SOCIALES, ESPECIALISTA EN GESTION AMBIENTAL', 'Administrador público con formación en políticas sociales y gestión ambiental, y experiencia como secretario de despacho.', 'SECRETARIOS DE DESPACHO', 'Decreto No. 007 del 01 de enero de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1112033-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EQqWRHKzW5lCvtqwBFwzVHABWX6-lnY_Ew86Fj-eHznnag?e=MqidaB'),
('50','REYES PINO YEFERSON', '3148901234', 'ESPECIALISTA EN PEDAGOGIA PARA LA DOCENCIA UNIVERSTIARIA', 'Especialista en pedagogía universitaria con experiencia como secretario de despacho.', 'SECRETARIOS DE DESPACHO', 'Decreto No. 236 del 31 de diciembre de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S3127309-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/QnRvDjKwOxMgZnYcPgTkFuPoLqNzMxBtKoZpTyAbWcLoJw?e=CrXvPe'),
('51','NIETO MORA JHON ALEXANDER', '3159012345', 'CONTADOR PÚBLICO', 'Contador público con experiencia en dirección administrativa como director de IMDES.', 'DIRECTOR IMDES', 'Decreto No. 009 del 01 de enero de 2024', 'faltan documentos por cargar en el sigep', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EdUTz67fsttMkSiGTeyFGEABHnXDegUTmxGjYndMz7XSiw?e=wnMvrB'),
('52','NOVOA DIAZ JENNIFER YULIET', '3160123456', 'CONTADOR PUBLICO, ESPERCIALISTA EN REVISORIA FISCAL Y AUDITORIA FORENSE', 'Contador público, especialista en revisoría fiscal y auditoría forense, con experiencia como técnico administrativo.', 'TECNICO ADMINISTRATIVO', 'Resolución No. 130 del 28 de febrero de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S4902043-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EVYK9QDA4ylNlGaVFk5-Gh0Bp66JTG5hxWK4a61ZK2eTGQ?e=UY056x'),
('53','OLIVAR PAYANENE CESAR ANDRES', '3171234567', 'BACHILLER', 'Bachiller en Guardia Municipal, enfocado en seguridad y protección comunitaria.', 'GUARDIAN MUNICIPAL', 'Resolución No. 949 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S4628929-1039-4/view', 'carcel@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Ea34eZOzn69EnYR0jvjgm9gBMdew1KZXNFOGXzbxIH2MZg?e=8QWB4n'),
('54','OSORIO VELANDIA SANDRA PATRICIA', '3182345678', 'TECNÓLOGO EN GESTION DE RECURSOS NATURALES, ADMINISTRADORA DE EMPRESAS', 'Tecnóloga en gestión de recursos naturales y administradora de empresas con experiencia como técnico operativo.', 'TÉCNICO OPERATIVO', 'Resolución No. 876 del 2 de febrero de 2024', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1158230-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/LrMzJxNgPwQlTaXnCoUvEyPvMuZnKjGbFxMcZhWrAqYoTg?e=VbPwKr'),
('55','OSPINA HUERTAS JOSE LUIS', '3193456789', 'BACHILLER', 'Bachiller con experiencia en conducción y transporte seguro.', 'CONDUCTOR', 'Contrato Individual de Trabajo a Términio Indefinido ', 'N/A', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EVx8_QgJOcBCqrhcmep2nMYBTSm2xUAKbVQOBBDtkcBPCQ?e=02QVaq'),
('56','OTALORA GUTIERREZ FERNANDO', '3204567890', 'TECNÓLOGO EN GESTION ADMINISTRATIVA, TECNICO LABORAL EN TRABAJO SOCIAL Y COMUNITARIO', 'Tecnólogo en gestión administrativa y técnico en trabajo social, con experiencia como almacenista.', 'ALMACENISTA', 'Decreto de Nombramiento No. 026 del 10 de enero de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S3140152-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/ZpFrLbQoNyRxTmVaAcGyPoFdKqLcXyZrTvNaPoYqKjFgLg?e=NtRuHq'),
('57','PARDO NORATO NOLBERTO', '3215678901', 'BACHILLER', 'Bachiller, Celador Municipal con enfoque en seguridad y orden público.', 'CELADOR MUNICIPAL', 'Resolución No. 957 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S2225568-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/ToHkUyApVbKgMxZcRfPnDjYlPaRxFbGaYtKoVcQmLrAuOw?e=KwLmFe'),
('58','PARRA DE SANCHEZ ANA BEATRIZ', '3226789012', 'BACHILLER', 'Bachiller, Auxiliar Administrativo con habilidades en gestión documental y atención al cliente.', 'AUXILIAR ADMINISTRATIVO', 'Decreto No. 425 del 10 de agosto de 2023', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1158232-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EcXpZgVtMcYlQwLbBrWnHgPaKqMvOcFtNgJzUrLqPfAyWw?e=ZoFgTr'),
('59','PEREZ ORJUELA ANACELIS', '3248901234', 'SECRETARIADO GENERAL - SENA', 'Secretariado General SENA, Secretario Ejecutivo con habilidades en gestión administrativa y atención ejecutiva.', 'SECRETARIO EJECUTIVO', 'Resolución No. 409 del 19 de mayo de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1158235-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EcCxTYMxm9JCoDIk8NXK5ecB5T2mW95Kch6SE7iIfKVQQA?e=11J7Bb'),
('60','QUIMBAYO OSPINA JOSE ANTONIO', '3271234567', 'BACHILLER', 'Bachiller con experiencia como Guardián Municipal en control y vigilancia comunitaria.', 'GUARDIAN MUNICIPAL', 'Resolución No. 944 del 8 de noviembre de 2022', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S702415-1039-4', 'carcel@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/JxNlQwPaVeLtXbOjPmRcZwKfOyGpKvAdWbHuMyLgNzRxAw?e=UgNwRq'),
('61','OLARTE LOPEZ ROBIN ANDRES', '3282345678', 'ADMINISTRADOR DE EMPRESAS, ESPECIALISTA EN GERENCIA Y GESTION DE SERVICIOS DE SALUD', 'Administrador de Empresas, especialista en salud, con experiencia como Director de Cárcel Municipal.', 'DIRECTOR CÁRCEL MUNICIPAL', 'Decreto No. 041 del 10 de marzo de 2025', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S778805-1039-4', 'carcel@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/MqVdKtNcYePlQoAtUbFyTxLzPvMgFrYqGmNkWbAvZcXnJw?e=XuTpVa'),
('62','RENDON MIRANDA LORENA CLEMENTINA', '3293456789', 'TECNICO EN ADMINISTRACIÓN PUBLICA', 'Técnico en Administración Pública, especializado en la gestión de servicios generales.', 'AUXILAIR SERVICIOS GENERALES', 'Resolución No. 462 del 28 de junio de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S938196-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EZLIGoX0A99KiJTqg9TdFswBhXThBKVNpThnmvfR3hZsJg?e=7gKSkK'),
('63','RESTREPO TORO DOLLY ESPERANZA', '3004567890', 'TECNICO EN ADMINISTRACION DEL TALENTO HUMANO', 'Técnico en Administración del Talento Humano, con experiencia en apoyo administrativo y gestión de recursos humanos.', 'AUXILIAR ADMINISTRATIVO', 'Decreto No. 263 del 3 de agosto de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S751821-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Eed25uR3Q7VBgvkvSH-Xs8ABkL_u696G8vkx7KZQginfhQ?e=z34hPF'),
('64','RIVERA FLORES GILBERTO ALEXI', '3015678901', 'BACHILLER', 'Bachiller con formación en operación de maquinaria, especializado en el manejo y mantenimiento básico de equipos.', 'OPERADOR DE MAQUINARIA 1', 'Contrato Individual de Trabajo a Términio Indefinido ', 'N/A', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EQ0npP_tJU1Ks-xGeLPNEWYBWdxXaPZVGOro2ViKNiGB_A?e=OJ0www'),
('65','RODRIGUEZ GONZALEZ NIYERETH', '3026789012', 'TECNOLOGO EN GESTION ADMINISTRATIVA', 'Tecnólogo en Gestión Administrativa y Secretario Ejecutivo, con experiencia en apoyo administrativo y organización.', 'SECRETARIO EJECUTIVO', 'Resolución No. 146 del 8 de marzo de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1938331-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EY02WbUb8O5IjlCEzYF-hVgBTGLxPontw41nBJ2JHrDfHQ?e=cDMFJt'),
('66','RODRÍGUEZ ROJAS WILLY ALEJANDRO', '3048901234', 'ZOOTECNISTA, ESPERACIALISTA EN GOBIERNO Y GESTION PUBLICA TERRITORIAL', 'Zootecnista y especialista en Gestión Pública Territorial, con experiencia como Alcalde Municipal.', 'ALCALDE MUNICIPAL', 'Certificado E14 Registraduría Nacional del Estado Civil', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S3142133-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Ea5uCXngAAlAgafVCcZDgOIB7ELiGBJxnlSlKpDBFUougQ?e=SeqfZP'),
('67','RODRIGUEZ TRIANA LUIS', '3059012345', 'BASICA PRIMARIA', 'Bachiller con formación en operación de maquinaria, especializado en el manejo de equipos básicos.', 'OPERADOR DE MAQUINARIA 1', 'Contrato Individual de Trabajo a Términio Indefinido ', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S4245988-0680-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/VoDjUwMqKzWyAoPrFxNgPcJyLrTnZqFbEpYiMqXlBtKwTw?e=NpFtVx'),
('68','ROJAS CARDONA ZUNILDA', '3060123456', 'TECNICO EN ADMINISTRACION FINANCIERA Y AUDITORIA', 'Operador de maquinaria con experiencia en equipos pesados y enfoque en seguridad.', 'AUXILIAR ADMINISTRATIVO', 'Resolución No. 664 del 31 de agosto de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1158239-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Ee7sxXYFv3NGtLMFb4cd5n8BeP4pT_WsxiPFEoUOrpp3wg?e=HZNXfQ'),
('69','ROMERO MURCIA ANGELICA JHOANA', '3071234567', 'CONTADORA PUBLICA', 'Contadora pública y técnico administrativo con experiencia en gestión financiera y contable.', 'TECNICO ADMINISTRATIVO', 'Resolución No. 946 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S4628814-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/DtXvPyGmNrAyWcLjFoVpRbZmMjTyKoFqRaTnWmYxCgPlQw?e=QdXrNj'),
('70','SANABRIA OMAÑA VIRGILIO', '3082345678', 'BACHILLER', 'Bachiller con experiencia como ayudante, dispuesto a apoyar en diversas tareas y aprender rápidamente.', 'AYUDANTE', 'Contrato Individual de Trabajo a Términio Indefinido ', 'N/A', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Eeyknb1OYaBOvwdZYupBYnoBDPoiqZZAzkSMUtzXOPNqqQ?e=Ok6Tmm'),
('71','SANCHEZ VARGAS CARLOS FAVIO', '3093456789', 'BACHILLER', 'Bachiller con experiencia como guardián municipal, comprometido con la seguridad y el orden público.', 'GUARDIAN MUNICIPAL', 'Resolución No. 951 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1158243-1039-4/view', 'carcel@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/GkXyOtBzQnWjPmKfVrDbLoZtUyXaCvWmKhNaRpXtMeKwPw?e=RwXpYe'),
('72','SILVA GARZON MILTON FARLEY', '3115678901', 'TECNICO EN PROMOCION AMBIENTAL', 'Técnico en Promoción Ambiental con experiencia en gestión y conservación de recursos naturales.', 'GUARDIAN MUNICIPAL', 'Resolución No. 947 del 8 de noviembre de 2022', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S854622-1039-4/view', 'carcel@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/AcTlVxYqOpZfNrWyLgQvFjKuRmTnBoPaZjUyRxFbNoWkFw?e=EoLgVs'),
('73','TOVAR CORTES MARIA ELVIRA', '3126789012', 'ECONOMISTA, ESPECIALISTA EN CONTRATACION ESTATAL', 'Economista y especialista en contratación estatal, con experiencia como secretario ejecutivo.', 'SECRETARIO EJECUTIVO', 'Resolución No. 990 del 9 de noviembre de 2022', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1158245-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EbHf5MqJOZNLsMsszU1lT8gBkcR0oFU4Y18BjcJ3W3e-Hg?e=PvHcdD'),
('74','VALDERRAMA MURCIA RICARDO ANDRES', '3137890123', 'ADMINISTRADOR DE EMPRESAS AGROPECUARIAS', 'Administrador de Empresas Agropecuarias con experiencia en gestión del sector agrícola y ganadero.', 'PROFESIONAL UNIVERSITARIO 03', 'Resolución No. 452 del 27 de junio de 2023', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1290618-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/YjBoTcKrNwGqUzAxPfYcZmVoWqLyKtCmGtMpFvZaQbNlKw?e=WcZyMu'),
('75','VALLEJO ALFONSO SEBASTIAN', '3148901234', 'BACHILLER', 'Bachiller con experiencia como ayudante, proactivo y dispuesto a aprender.', 'AYUDANTE', 'Contrato Individual de Trabajo a Términio Indefinido ', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1930898-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EQXCLb9LyNBEiGZDzCi8Vg0BqZOnHai_wM0kiKdrDjsF7Q?e=13YGTg'),
('76','VALOYES BENITEZ LEDYS MAGALI', '3159012345', 'ADMINISTRADOR AMBIENTAL', 'Administrador Ambiental con enfoque en la gestión sostenible y conservación de recursos naturales.', 'SECRETARIO EJECUTIVO', 'Resolución No. 147 del 8 de marzo de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1506860-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EUSFDcN3PuZGoa0wEI09PPMBtgfGgyeuwVFSZTe6_SIwCQ?e=b5s06h'),
('77','LOPEZ GUEVARA KEVIN JULIAN', '3160123456', 'ARQUITECTO', 'Arquitecto y Director Técnico de Obras con experiencia en la planificación y supervisión de proyectos constructivos.', 'DIRECTOR TECNICO OBRAS', 'Decreto No. 241 del 31 de diciembre de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S5057669-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/RuXvZyTpKgMvLfCnXmYjQBV5OtPvFrLmKcAfTwPiBhRq4Q?e=YpFgWd'),
('78','VERGARA URREGO CEIDA', '3171234567', 'ADMINISTRADORA PÚBLICA, ESPECIALISTA EN GESTION PUBLICA', 'Administradora Pública y especialista en Gestión Pública, con experiencia como Secretaria de Despacho.', 'SECRETARIOS DE DESPACHO', 'Decreto No. 005 del 01 de enero de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1930898-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EZjgbfGtAllJl-g7eHFH8_EBp0f5DjCVxKkcw77y4Eg1OQ?e=FYxRo2'),
('79','VILLADA VALENCIA BLANCA AYDEE', '3182345678', 'TECNÓLOGO EN CIENCIAS DE LA SALUD, TECNÓLOGO EN URBANISMO', 'Tecnólogo en Ciencias de la Salud y Urbanismo, con formación en gestión técnica administrativa.', 'TECNICO ADMINISTRATIVO', 'Resolución No. 056 del 6 de septiembre de 2023', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S1158247-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/ZqLtKwRyDmVzOyUcFbYtPaNqWzXrCoPvAmXtGbKyOdLpWg?e=FuXoNc'),
('80','YEPES PORRAS LUISA DELIA', '3205678901', 'BACHILLER', 'Bachiller con experiencia como auxiliar en servicios generales y apoyo operativo.', 'AUXILAIR SERVICIOS GENERALES', 'Resolución No. 245 del 24 de mayo de 2024', 'https://www1.funcionpublica.gov.co/web/sigep2/hdv/-/directorio/S909370-1039-4/view', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.', 'https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/KmPqLtXyNvAwZoFbDrJxTyRmPwFqNgUvYzWxQkOpLtYpEg?e=XvTaLs');

CREATE TABLE secretarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    apellidos_nombres VARCHAR(255) NOT NULL,
    telefono_institucional VARCHAR(20),
    profesion VARCHAR(100),
    perfil TEXT,
    cargo VARCHAR(100),
    decreto VARCHAR(100),
    enlace_sigep VARCHAR(255),
    correo_electronico_institucional VARCHAR(255),
    direccion VARCHAR(255),
    horario_trabajo VARCHAR(100),
    enlace_foto VARCHAR(255),

    id_funcionario INT,  

    CHECK (CHAR_LENGTH(apellidos_nombres) > 5),
    CHECK (correo_electronico_institucional LIKE '%@%'),

    CONSTRAINT fk_funcionario
      FOREIGN KEY (id_funcionario) REFERENCES funcionarios(id)
      ON DELETE SET NULL
      ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

drop table secretarios;
select * from secretarios;

INSERT INTO secretarios 
(id, apellidos_nombres, telefono_institucional, profesion, perfil, cargo, decreto, enlace_sigep, correo_electronico_institucional, direccion, horario_trabajo, enlace_foto) 
VALUES 
('1','MOSQUERA MORALES ARIEL', '3183971528', 'ADMINISTRADOR PÚBLICO, ESPECIALISTA EN GESTION Y PLANIFICACION DE POLÍTICA SOCIAL, MAESTRIA EN POLICITVAS SOCIALES, ESPECIALISTA EN GESTION AMBIENTAL', 'Administrador Público, Especialista en Gestión Ambiental y Especialista en Planificación y Gestión de Políticas Sociales Con 12 años de experiencia en el sector público, se destaca en su trayectoria laboral la formulación de proyectos y políticas públicas.', 'SECRETARIO DE PLANEACIÓN MUNICIPAL', 'Decreto No. 007 del 01 de enero de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1112033-1039-4', 'planeacion@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m.','https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EQqWRHKzW5lCvtqwBFwzVHABWX6-lnY_Ew86Fj-eHznnag?e=MqidaB'),
('2','ARROYO ARROYO ALBEIRO MIGUEL', '3107737815', 'ADMINISTRADOR DE EMPRESAS', 'Administrador de Empresas y Especialista en Gestión Pública Empresario independiente, con más de 15 años de experiencia en el sector público y privado.', 'SECRETARIO ADMINISTRATIVO Y DESARROLLO SOCIAL', 'Decreto No. 001 del 01/01/2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S1930898-1039-4', 'planeacion@sanjosedelguaviare-guaviare.gov.co', 'Calle 8 # 23 - 87 - barrio El Centro 2do piso', 'Lunes a viernes de 8:00 a.m. a 12:30 p.m. y de 2:00 a 6:00 p.m.','https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/EQv3iSb3i7pChhXXkoTDs7ABVzzl-Lf_CI7FCV907Jcgqw?e=x2fkX2'),
('3','MARCHENA ORTEGA ENITH MILENA', '3067890123', 'ABOGADA', 'Abogada especializada en asesoría legal para secretarías de despacho y gestión de procedimientos administrativos.', 'SECRETARIA JURÍDICO MUNICIPAL', 'Decreto No. 216 de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S864352-1039-4', 'juridica@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.','https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/RAoTLPJvBzXKFYWq9MUHwdmEoCNgAZQct3x75nblO2spy1?e=MfZx3a'),
('4','ACEVEDO ORTEGA DANIEL EDGARDO', '6085840889', 'COMUNICADOR SOCIAL ', 'Comunicador social con experiencia en gestión pública, desempeñándose como secretario de Tránsito y Transporte Municipal, enfocado en la movilidad y la comunicación estratégica.', 'SECRETARIO DE TRÁNSITO Y TRANSPORTE MUNICIPAL', 'Decreto No. 005 del 20 de julio de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S2816173-1039-4', 'transitoytransporte@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 19-115 barrio El Porvenir', 'Lunes a viernes de 8:00 a.m. a 12:30 p.m. y de 2:00 a 6:00 p.m.','https://soysena-my.sharepoint.com/:u:/g/personal/luisaf_barbosas_soy_sena_edu_co/ERxXVE0Wah5GnYkH8xtMXuMBAmxr0jyBg84NizTPYOZxEw?e=wh21sY'),
('5','SYLVIA NAIDU FONSECA GARCÍA', '3209094795', 'MEDICA, ESPECIALISTA EN GERENCIA EN SALUD', 'Enfoque en administración transparente y segura de recursos públicos, aplicando sus conocimientos para fortalecer el accionar de la Alcaldía.', 'SECRETARIA DE SALUD MUNICIPAL', 'Decreto No. 003 del 01 de enero de 2024', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S352452-1039-4', 'salud@sanjosedelguaviare-guaviare.gov.co', 'Calle 8 # 23-87, barrio El Centro - 1er piso', 'Lunes a viernes de 8:00 a.m. a 12:30 p.m. y de 2:00 a 6:00 p.m.','https://soysena-my.sharepoint.com/:u:/g/personal/luisaf_barbosas_soy_sena_edu_co/EbxbQJducnZCuHirUCTG8S8BB9uLrtdfBOYyDJKmEs607w?e=k6XDCK'),
('6','PINO REYES YEFERSON', '3168749621', 'DOCENTE - ESPECIALISTA EN LÚDICA EDUCATIVA', 'Docente y especialista en lúdica educativa, actualmente secretario de Educación Municipal, comprometido con el fortalecimiento de la calidad educativa a través de metodologías innovadoras.', 'SECRETARIO DE EDUCACIÓN MUNICIPAL', 'Decreto No. 008 del 04 de abril de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S3127309-1039-4', 'educacion@sanjosedelguaviare-guaviare.gov.co', 'Calle 8 N° 23 - 87, barrio El Centro 1er piso', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.','https://soysena-my.sharepoint.com/:u:/g/personal/luisaf_barbosas_soy_sena_edu_co/EbxbQJducnZCuHirUCTG8S8BB9uLrtdfBOYyDJKmEs607w?e=k6XDCK'),
('7','LOPEZ GUTIERREZ EDWIN', '3108643110', 'INGENIERA AGROFORESTAL', 'Ingeniero agroforestal al frente de la Secretaría de Desarrollo Productivo y Ambiental, enfocado en la sostenibilidad, el impulso del sector rural y la conservación de los recursos naturales.', 'SECRETARIA DE DESARROLLO PRODUCTIVO Y AMBIENTAL', 'Decreto No. 009 del 16 de enero de 2023', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S341838-1039-4', 'desarrolloproductivoyambiental@sanjosedelguaviare-guaviare.gov.co', 'calle 10 # 24-11 barrio El Centro', 'Lunes a viernes de 7:00 a.m. a 12:00 m. y 2:00 a 5:00 p.m.','https://soysena-my.sharepoint.com/:u:/g/personal/luisaf_barbosas_soy_sena_edu_co/EcNvFNDZ0R1HpIS642eylFkBcJ9AafzddQKY3IsCmflUUA?e=NP2htL'),
('8','RODRÍGUEZ ROJAS WILLY ALEJANDRO', '3103413509', 'ZOOTECNISTA, ESPERACIALISTA EN GOBIERNO Y GESTION PUBLICA TERRITORIAL', 'DESPACHO DEL ALCALDE', 'Zootecnista y especialista en Gestión Pública Territorial, con experiencia como Alcalde Municipal.', 'Certificado E14 Registraduría Nacional del Estado Civil', 'https://www.funcionpublica.gov.co/dafpIndexerBHV/hvSigep/detallarHV/S3142133-1039-4', 'contactenos@sanjosedelguaviare-guaviare.gov.co', 'Carrera 24 # 7-80, barrio El Centro', 'Lunes a jueves de 8:00 a.m. a 12:30 p.m. y 2:00 a 6:00 p.m. y viernes de 8:00 a.m. a 12:30 p.m. y 2:00 a 5:00 p.m.','https://soysena-my.sharepoint.com/:i:/g/personal/luisaf_barbosas_soy_sena_edu_co/Ea5uCXngAAlAgafVCcZDgOIB7ELiGBJxnlSlKpDBFUougQ?e=SeqfZP');

SELECT 
    id,
    apellidos_nombres,
    telefono_institucional,
    profesion,
    perfil,
    cargo,
    decreto,
    enlace_sigep,
    correo_electronico_institucional,
    direccion,
    horario_trabajo,
    enlace_foto
FROM funcionarios

UNION

SELECT 
    id,
    apellidos_nombres,
    telefono_institucional,
    profesion,
    perfil,
    cargo,
    decreto,
    enlace_sigep,
    correo_electronico_institucional,
    direccion,
    horario_trabajo,
    enlace_foto
FROM secretarios;
